# Generated by Django 3.2.6 on 2022-07-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_image_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='credits_date',
            new_name='create_date',
        ),
    ]
