# Generated by Django 4.0.6 on 2022-07-30 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variations',
            new_name='variation',
        ),
    ]
